apiVersion: ververica.platform/v1
kind: VvpDeployment
metadata:
  name: tsw-argocd-02
  namespace: vvp
  annotations:
    apikeySecretName: apikey-secret
    # Add ArgoCD tracking annotation - this is the key part
    argocd.argoproj.io/tracking-id: vvp:ververica.platform/VvpDeployment:vvp/tsw-argocd-02
    # Optional: Configure how ArgoCD compares this resource
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncingMode: PATCH
  deployment:
    userMetadata:
      name: tsw-argocd-02
      namespace: default
      # Add labels that will be propagated to child resources
      labels:
        app: tsw-argocd-02
        managed-by: argocd
      # Add annotations that will be propagated to child resources  
      annotations:
        argocd.argoproj.io/tracking-id: vvp:ververica.platform/VvpDeployment:vvp/tsw-argocd-02
    spec:
      state: RUNNING
      deploymentTargetName: vvp
      maxJobCreationAttempts: 3
      upgradeStrategy:
        kind: STATEFUL
      restoreStrategy:
        kind: LATEST_STATE
      template:
        spec:
          artifact:
            flinkImageRegistry: registry.ververica.com/v2.15
            flinkImageRepository: flink
            flinkImageTag: 1.20.1-stream1-scala_2.12-java11
            flinkVersion: '1.20'
            jarUri: s3://naci-bucket/artifacts/namespaces/default/TopSpeedWindowing.jar
            kind: JAR
          resources:
            jobmanager:
              cpu: 0.2
              memory: 1g
            taskmanager:
              cpu: 0.2
              memory: 1g
          flinkConfiguration:
            high-availability: kubernetes
            execution.checkpointing.interval: 25s
            restart-strategy: fixed-delay
            restart-strategy.fixed-delay.attempts: '2'
